### ISSUE TITLE
Translation into Spanish.

### ISSUE THREAD

**Issue by vidimus** [abedgregio/MoM#1]
Hello, @abedgregio 

Would you mind if I translate your scenario into Spanish? Are you available for updating the translation file when I finish it?

By the way, the scenario title, is it literal or in this case is about losing the temper? It'd be quite hard to find  a similar expression in Spanish in case that you are playing on words with both meanings...

**Comment by abedgregio** [comment]
Dear Vidimus,

It would be great if you could translate. I’d update the scenario as soon as you send the translation text. Thanks a lot. ☺️

**Comment by abedgregio** [comment]
> Hello, @abedgregio
> 
> Would you mind if I translate your scenario into Spanish? Are you available for updating the translation file when I finish it?
> 
> By the way, the scenario title, is it literal or in this case is about losing the temper? It'd be quite hard to find a similar expression in Spanish in case that you are playing on words with both meanings...

The title is literal (as if Father Mateo begins to doubt about his own beliefs). I planned 3 intertwined scenarios with names of famous songs: this one, with the REM title, the next one will be Sympathy for the Devil (I’ve just started the map), and the last one will be called Keep the Faith (the script is a rough draft right now)...

**Comment by vidimus** [comment]
Great, thanks for the clarification. With the first one, I've exactly got in mind the REM song as I saw the scenario title. And so it was my question, cause in the song, the meaning is not literal.

Good luck doing the other 2 scenarios.

**Comment by vidimus** [comment]
Hello, @abedgregio 

I've finished the translation. The file is here:
https://github.com/vidimus/Valkyrie-Mom-scenarios-translations/files/5053880/Localization.Spanish.txt

Repo: https://github.com/vidimus/Valkyrie-Mom-scenarios-translations/issues/27#issuecomment-671633826

Just in case, do you know what do you have to do to update the scenario with the translation?

By the way, can I suggest you to change the title to something like "Father Mateo - Part I - Losing my faith" . It's just to get the scenarios linked with the name. Otherwise, people could be confuse seeing different scenario names with nothing in common.

Plus, I found some bugs when testing the translation. I will make a list tomorrow in order to help you correcting them (with some screenshots if possible).

**Comment by abedgregio** [comment]
Dear @vidimus, 

Thank you so much. I've already uploaded the localization file to this repo.

> Just in case, do you know what do you have to do to update the scenario with the translation?

Not really... I can check scrubless tutorial and fix that in the weekend, but any help is welcome. =)

>  ... can I suggest you to change the title to something like ...

Sure! I could change the title to "Mateo Quest, part I - Losing my religion". Would you mind if we exchange emails? It would be great if you send me the bugs you found, so I can correct them, as well as the name of the scenario and add the translation, then we could announce it on BGG. Thanks again!

A.

**Comment by vidimus** [comment]
Hello, @abedgregio 

If you follow the tutorial I think you'd have no problems to update the scenario with the translation. In case of doubt, please, post here a comment and I will try to help you.

About the name, "Mateo Quest" doesn't sound very epic, in my modest opinion. Maybe something that links the 3 scenarios, some kind of leitmotiv?.

About the bugs, most of them are related to Grace Bechman. Fine to send you the info. Feel free to give me the email and I will send you the pics, or I can post them here. Whatever!

**Comment by abedgregio** [comment]
Hi @vidimus, my email is the github's username at GMail, but feel free to post bugs here. Whatever is best for you.
Maybe a suitable name to embrace all scenarios would be "Losing my religion, part I - The devil in her heart", then all three parts would start with losing my religion... How does it sound for you?

**Comment by vidimus** [comment]
It sounds fine to me. In Spanish, if you want to update the scenario name on the translation is:
Perdiendo la fe, primera parte - El demonio en su corazón.
In Spanish we don't make the difference between her/him, so it could be a bit ambiguous. Not a real problem, I think.

About the problems on the scenario:

- On the first turn, if you speak twice with Richard, he went out, finishing the dinner. But on the next Mythos phase it happened the "earthquake" and the dialogue describes that you are still on the table, dinning with Grace. Maybe Richard should wait one more turn on the table.

And now, others issues with pictures: 

- Here, maybe the test should gives to the investigator the amount of successes to pass it.

![Captura de pantalla (387)](https://user-images.githubusercontent.com/41538948/90311982-fca6b800-df00-11ea-87fd-23e9e8a512fa.png)


- If you trigger the attic event, Grace appears close to you, but if she was first in the girls bedroom, the token remains there, and so the dialogue and options.


![Captura de pantalla (388)](https://user-images.githubusercontent.com/41538948/90311986-ffa1a880-df00-11ea-8513-a98a60fa431e.png)


- When Grace runs for the telephone, she didn't move at all. I tried for 20 turns, and nothing, she didn't move any space to the phone. And she didn't react to Richard's death.

![Captura de pantalla (389)](https://user-images.githubusercontent.com/41538948/90311987-03352f80-df01-11ea-87ea-0fe268a09f23.png)


- This is not a bug, just I'm curious how the devil event could be triggered. I tried a lot of times and never get the text with the Nightgaunt (to check the translation, btw). How can I get the devil spawned in the attic?

![Captura de pantalla (386)](https://user-images.githubusercontent.com/41538948/90311989-05978980-df01-11ea-930b-a3ac3a3bd1cf.png)

**Comment by abedgregio** [comment]
@vidimus, thanks a lot for the translation and the bug hunting! I'll fix all of them ASAP and update the scenario with your work. 
 
Some comments:
- I think I´ll put a turn counter on Richard so he waits for the first event before leaving. I've struggled a little with the dinner scene. In fact, in a future update, maybe I'll redo this entire scene. 
- There were other occurrences of Grace's double appearances, but this one remained... =(
- I really did not test enough the act in which Grace runs towards the phone. Will try to fix it entirely. 
- If you manage to get the key to the upstairs door (passing the test with Pazuzu, the dog, inside the girl´s room), instead of forcing it open, you'll face the devil himself in the attic. =)

Many, many thanks!

**Comment by vidimus** [comment]
@abedgregio No problem,  Thanks to you for creating the scenario.

I will replay it again. If I see any other problem, I will post it here. And if you change the text or add new entries, please let me know it so I could translate them.

**Comment by abedgregio** [comment]
@vidimus,

I tried to fix the Grace running ending and added some text. I've also translated this new part (you can check if it is ok if you want), and added the name of the translation file to the quest.ini file. However, the Spain flag is not appearing for me after updating the github and reimporting content in Valkyrie. Could you verify if the Spanish option is available for you, please?
Thanks again!

> @abedgregio No problem, Thanks to you for creating the scenario.
> 
> I will replay it again. If I see any other problem, I will post it here. And if you change the text or add new entries, please let me know it so I could translate them.

**Comment by abedgregio** [comment]
@vidimus, now it appeared! =/

**Comment by vidimus** [comment]
Hello, @abedgregio 

I've corrected the issue with the ending text.
[Localization.Spanish.txt](https://github.com/abedgregio/MoM/files/5360373/Localization.Spanish.txt)

**Comment by vidimus** [comment]
Hello, @abedgregio 
I've seen your new scenario, Reanimator 1. I will translate it into Spanish as soon as you tell me it's ready to be translated. I guess you would like to tune it a bit with user's comments, right?

**Comment by abedgregio** [comment]
> Hello, @abedgregio
> I've seen your new scenario, Reanimator 1. I will translate it into Spanish as soon as you tell me it's ready to be translated. I guess you would like to tune it a bit with user's comments, right?

Dear @vidimus,
Thanks again for your interest and effort. =)

I'm almost finishing the English translation, so feel free to translate the current version. I hope to get comments/suggestions from the Spanish community to tune stuff, if needed. However, it's a very short scenario with a direct objective (more like a dungeon crawl): the investigators have to find and destroy some experiments, fight some monsters and a mini-boss, and see what the story reserves for the further adventure... I'm now finishing the part 2, which will advance the story and will be as direct as the part 1 (in p.2, you have to find a place and rescue a person).

Best,

Andre

**Comment by vidimus** [comment]
Yes, it's quite short. I would probably do it this week.
One thing I saw on the scenario:
When the assistant gives you the torch, there's no item card showed.  Is this intended? It could be confusing for some players, in my modest opinion.

And this is just a very personal comment. I dislike the image chosen for the scenario. It's quite futuristic, it's like an organic robot and it breaks the general scenario mood. Surfing the net for a free common creative image gives a lot of alternatives.

**Comment by abedgregio** [comment]
> Yes, it's quite short. I would probably do it this week.
> One thing I saw on the scenario:
> When the assistant gives you the torch, there's no item card showed. Is this intended? It could be confusing for some players, in my modest opinion.
> 
> And this is just a very personal comment. I dislike the image chosen for the scenario. It's quite futuristic, it's like an organic robot and it breaks the general scenario mood. Surfing the net for a free common creative image gives a lot of alternatives.

@vidimus, thanks for the suggestions. I did not give the torch at first because I thought it was an item from Path of Serpent. However, I found the physical card as a "Base" item, but did not find it in Valkyrie as Base, just as PoS. Anyway, I've added the torch hoping that it doesn't create the need of enabling PoS for players... =)

Completely agree with your opinion on the cover/start image. I've changed the cover to resemble a fire-ish zombie with an image from Valkyrie and the start image to another "official" one. Do you have a fixed place to obtain Free/CC images? All the interesting ones I found were on AdobeStock or PhotoStock and expensive.

Anyway, thanks again. These changes caused minor alterations to the text (the torch event and a new sentence on the ending).

**Comment by vidimus** [comment]
Ok, @abedgregio , I will make the changes in my translation file. I think I could finish it in just a couple of days (it's quite short, and I really like the theme, so I set aside other projects for a few days to finish this one).

About the CC images, I just surf the net using google. By the way, on Soundcloud there are some interesting free-to-use soundtracks, some of them quite appropriate for MoM scenarios.

**Comment by vidimus** [comment]
One thing more, in Spanish, the novel and the movie were called "Herbert West, reanimador". Would you mind if I put that on the Spanish title instead of just "Reanimator"?

**Comment by vidimus** [comment]
https://es.wikipedia.org/wiki/Herbert_West:_reanimador#/media/Archivo:Doctor_Herbert_West_by_Javier_Garc%C3%ADa_Ure%C3%B1a.jpg

This one is on the wikipedia about the Reanimator novel. It's CC BY-SA 3.0
![Doctor_Herbert_West_by_Javier_García_Ureña](https://user-images.githubusercontent.com/41538948/104224348-2844b480-5445-11eb-97cf-0e16b7991fa4.jpg)
Maybe you can use it for the second part. You have the contact on the wikipedia link.

**Comment by abedgregio** [comment]
> https://es.wikipedia.org/wiki/Herbert_West:_reanimador#/media/Archivo:Doctor_Herbert_West_by_Javier_Garc%C3%ADa_Ure%C3%B1a.jpg
> 
> This one is on the wikipedia about the Reanimator novel. It's CC BY-SA 3.0
> ![Doctor_Herbert_West_by_Javier_García_Ureña](https://user-images.githubusercontent.com/41538948/104224348-2844b480-5445-11eb-97cf-0e16b7991fa4.jpg)
> Maybe you can use it for the second part. You have the contact on the wikipedia link.

Thank you! I'll use it. Feel free to translate the mission title to Herbert West, Reanimator... I'm just finishing to fix some typos and images, and then I'll upload the second part. Regarding sound effects: I always forget to add them. =/ One thing to remember in future scenarios or updates.
